#!/usr/bin/env node
import fs from 'node:fs';
import crypto from 'node:crypto';
import {spawnSync} from 'node:child_process';
const RECEIPT="data/review/adapter-sdk/star-trek-lwaxana-eligibility-rejection/receipt.json";
const EXPECTED_RECEIPT="172f506624b13c6bdeb97bd8f1d5982afa15883e17a5a74b24dfe4495de5f0b2";
const TASK="ap_a65494e8328ca262d82a49c0";
const FINGERPRINT="f5b48cb2179b2192e0c02eedfb417a891278757693c31fd9dea19cb5351e132f";
const WALL="UC-1391";
const EXPECTED_PARENT="a5ec2df6accd3216b2dafce98189167ffe3c882a";
const PRODUCT_PREDECESSOR="47296e8a7947384b04275962b8f6a125e5306680";
const read=path=>JSON.parse(fs.readFileSync(path,'utf8'));
const sha=value=>crypto.createHash('sha256').update(value).digest('hex');
const stable=value=>Array.isArray(value)?value.map(stable):value&&typeof value==='object'?Object.fromEntries(Object.keys(value).sort().map(key=>[key,stable(value[key])])):value;
const pretty=value=>JSON.stringify(stable(value),null,2)+'\n';
const jsonl=path=>fs.readFileSync(path,'utf8').split(/\r?\n/).filter(Boolean).map(JSON.parse);
const ok=(condition,message)=>{if(!condition)throw new Error(message)};
const receipt=read(RECEIPT), body=structuredClone(receipt); delete body.receipt_sha256;
ok(receipt.receipt_sha256===EXPECTED_RECEIPT&&receipt.receipt_sha256===sha(pretty(body)),'Lwaxana rejection receipt identity drifted');
ok(receipt.canonical_parent===EXPECTED_PARENT&&receipt.direct_parent.commit===EXPECTED_PARENT&&receipt.product_predecessor.commit===PRODUCT_PREDECESSOR,'Lwaxana predecessor binding drifted');
ok(receipt.adjudication.classification==='ineligible / no card'&&receipt.adjudication.card_created===false&&receipt.adjudication.media_bound===false&&receipt.adjudication.public_route_created===false,'Lwaxana eligibility boundary drifted');
for(const [path,expected] of Object.entries(receipt.support))ok(sha(fs.readFileSync(path))===expected,'Lwaxana support file drifted: '+path);
const state=read('data/AUTOPILOT.json'), tasks=state.jobs.filter(row=>row.id===TASK);
ok(tasks.length===1,'Lwaxana task cardinality drifted');
const task=tasks[0];
ok(task.scope==='star-trek'&&task.performer==='Majel Barrett'&&task.character==='Lwaxana Troi'&&task.source_fingerprint===FINGERPRINT&&task.status==='rejected','Lwaxana rejected task drifted');
ok(task.outcome?.kind==='rejection'&&task.outcome.reason===receipt.decision.reason&&task.outcome.decided_by===receipt.decision.decided_by,'Lwaxana rejection outcome drifted');
ok((task.wall_ids||[]).length===0&&!task.lease,'Lwaxana rejection acquired a wall or active lease');
ok(!read('data/specimens.json').some(row=>row.id===WALL),'Lwaxana card was created');
ok(!read('data/SOURCES.json').some(row=>row.id===WALL),'Lwaxana source ledger entry was created');
ok(!read('data/MEDIA-AUDIT.json').items.some(row=>row.wall_id===WALL),'Lwaxana media facets were created');
ok(!fs.readdirSync('images').some(name=>name.toLowerCase().startsWith('uc-1391-')),'Lwaxana image asset was created');
ok(!fs.readFileSync('sitemap.xml','utf8').includes('records/UC-1391/'),'Lwaxana public route was created');
const claims=jsonl('data/journal/autopilot.jsonl').filter(row=>row.op==='lease.claimed'&&row.lease_id===receipt.lease.id&&row.task_id===TASK);
const rejections=jsonl('data/journal/autopilot.jsonl').filter(row=>row.op==='task.rejected'&&row.lease_id===receipt.lease.id&&row.task_id===TASK);
ok(claims.length===1&&claims[0].id===receipt.lease.claim_event_id,'Lwaxana claim event drifted');
ok(rejections.length===1&&rejections[0].id===receipt.decision.event_id,'Lwaxana rejection event drifted');
const cycles=read('data/WATERLINE-STATE.json').cycles.filter(row=>row.lease_id===receipt.lease.id);
ok(cycles.length===1&&cycles[0].id===receipt.waterline.cycle_id&&cycles[0].outcome==='aborted'&&cycles[0].task_statuses?.[TASK]==='rejected','Lwaxana aborted cycle drifted');
const waterEvents=jsonl('data/journal/waterline.jsonl').filter(row=>row.id===receipt.waterline.event_id&&row.lease_id===receipt.lease.id);
ok(waterEvents.length===1&&waterEvents[0].outcome==='aborted','Lwaxana waterline event drifted');
const trek=state.jobs.filter(row=>row.scope==='star-trek');
ok(trek.length===receipt.queue.after.total,'Star Trek denominator drifted');
ok(trek.filter(row=>row.status==='rejected').length>=receipt.queue.after.rejected,'Star Trek rejected floor regressed');
ok(trek.filter(row=>row.status==='resolved').length>=receipt.queue.after.resolved,'Star Trek resolved floor regressed');
const prior=read(receipt.product_predecessor.receipt_path);
ok(sha(fs.readFileSync(receipt.product_predecessor.receipt_path))===receipt.product_predecessor.receipt_file_sha256&&prior.receipt_sha256===receipt.product_predecessor.receipt_identity,'Kukulkan receipt custody drifted');
ok(sha(fs.readFileSync(receipt.product_predecessor.checker_path))===receipt.product_predecessor.checker_sha256,'Kukulkan checker custody drifted');
const projection=fs.mkdtempSync('/tmp/lwaxana-kukulkan-projection-');
let priorRun;
try{
  const add=spawnSync('git',['worktree','add','--detach',projection,EXPECTED_PARENT],{encoding:'utf8',maxBuffer:256*1024*1024});
  ok(add.status===0,'Kukulkan compatibility projection could not be materialized: '+(add.stdout||'')+(add.stderr||''));
  priorRun=spawnSync(process.execPath,[receipt.product_predecessor.checker_path],{cwd:projection,encoding:'utf8',maxBuffer:256*1024*1024});
  ok(priorRun.status===0,'Kukulkan checker failed inside exact pre-rejection projection: '+(priorRun.stdout||'')+(priorRun.stderr||''));
}finally{
  spawnSync('git',['worktree','remove','--force',projection],{encoding:'utf8',maxBuffer:256*1024*1024});
}
console.log('star-trek-lwaxana-eligibility-rejection: PASS — exact Lwaxana task rejection, aborted-cycle closure, unchanged wall and media ledgers, no designed-face or maker inference, immutable Kukulkan product custody, and later-cycle bounds are intact');
