transaction=STAR-TREK-BENBASSAT-PREPRODUCT-SETTLEMENT-V1
canonical=ed79424013b92460d16c01cad4e590eca01e6bff
source=agent/star-trek-benbassat-source-result-v3
source_review=agent/star-trek-benbassat-source-review-result-v1
claim=agent/star-trek-benbassat-claim-result-v1
media=agent/star-trek-benbassat-media-result-v1
task=ap_dd7d1c73ed237230cd6e1d0b
performer=Nolan North
character=Benbassat
wall_id_reserved=UC-1397
canonical_mutation=false
additional_lease=false
