  let checkerText = fs.readFileSync(checkerPath, 'utf8');
  const checkerTypo = '{total:trek.length,ueued,resolved,';
  ensure(checkerText.includes(checkerTypo), 'Maryl checker typo repair target missing');
  checkerText = checkerText.replace(checkerTypo, '{total:trek.length,queued,resolved,');
  fs.writeFileSync(checkerPath, checkerText);
  fs.chmodSync(checkerPath, 0o755);
  const checkerSha = shaFile(checkerPath);
  const sourceMediaVisualReview = readJson(path.join(stageRoot, 'source-media-visual-review.json'));

  const receiptBody = {
    version: 1,
    transaction: 'STAR-TREK-CYCLE-MARYL',
    generated_at: reviewedAt,
    canonical_parent: EXPECTED_MAIN,
    task: {
      id: TASK_ID,
      performer: PERFORMER,
      role: CHARACTER,
      production: PRODUCTION,
      years: YEARS,
      source: SOURCE,
      source_fingerprint: SOURCE_FINGERPRINT,
      source_receipts: [{ source: SOURCE, pageid: SOURCE_PAGEID, revision: SOURCE_REVISION, timestamp: SOURCE_TIMESTAMP, content_sha256: SOURCE_CONTENT_SHA256 }],
      episode_source: EPISODE_SOURCE,
      episode_receipt: EPISODE_RECEIPT,
      queued_mode_hint: ['physical-prosthetic'],
      adjudicated_kind: 'physical',
      performance_mode: 'physical-prosthetic',
      performance_scope: 'Jeri Ryan’s physical live-action performance as Maryl through Seven of Nine in Infinite Regress (1998)',
      erica_mer_scope: 'the separately depicted girl in reflection',
      original_maryl_body_inferred: false,
      erica_mer_reflection_conflated: false,
      maker_attribution: 'unresolved',
      prosthetic_design_attribution: 'unresolved',
      makeup_attribution: 'unresolved',
      costume_attribution: 'unresolved',
      direction_attribution: 'unresolved',
      editing_attribution: 'unresolved',
      sound_attribution: 'unresolved',
      production_shop_attribution: 'unresolved',
      transformation_measured: false,
    },
    lease: stageDoc.lease,
    candidate: {
      commit: env.CANDIDATE_COMMIT,
      tree: env.CANDIDATE_TREE,
      path_count: Number(env.CANDIDATE_PATH_COUNT),
      path_ledger_sha256: env.CANDIDATE_PATH_LEDGER_SHA256,
      stage_receipt_sha256: stageDoc.receipt_sha256,
      artifact: { id: Number(env.STAGE_ARTIFACT_ID), sha256: String(env.STAGE_ARTIFACT_DIGEST || '').replace(/^sha256:/, '') },
    },
    independent_review: {
      verdict: 'pass',
      review_sha256: reviewDoc.review_sha256,
      artifact: { id: Number(env.REVIEW_ARTIFACT_ID), sha256: String(env.REVIEW_ARTIFACT_DIGEST || '').replace(/^sha256:/, '') },
    },
    source_media: {
      workflow_run: Number(env.MEDIA_RUN),
      artifact: { id: Number(env.MEDIA_ARTIFACT), sha256: String(env.MEDIA_DIGEST || '').replace(/^sha256:/, '') },
      visual_review_sha256: sha(Buffer.from(stablePretty(sourceMediaVisualReview))),
      canonical_parent: MEDIA_CANONICAL_PARENT,
    },
    canonical: {
      wall_id: stageDoc.wall_id,
      record: card,
      outcome_review_sha256: task.outcome.review_sha256,
      record_sha256: sha(Buffer.from(stablePretty(card))),
    },
    media: {
      still: 'verified',
      still_path: card.still.src,
      still_origin: card.still.origin,
      still_sha256: shaFile(card.still.src),
      portrait: 'verified',
      portrait_path: card.portrait.src,
      portrait_origin: card.portrait.origin,
      portrait_author: card.portrait.author,
      portrait_license: card.portrait.license,
      portrait_sha256: shaFile(card.portrait.src),
      facets,
      facets_sha256: sha(Buffer.from(stablePretty(facets))),
      source_ledger_sha256: sha(Buffer.from(stablePretty(source))),
      cross_facet_substitution: false,
      maker_attribution: 'unresolved',
    },
    queue: {
      before: { total: 2228, queued: 1802, resolved: 424, blocked: 0, rejected: 2, in_flight: 0 },
      after: counts,
    },
    prior_custody: {
      task_id: 'ap_9b7123237c640f1ce0a16ffe',
      character: 'Lorot',
      receipt_path: PRIOR_RECEIPT_PATH,
      receipt_identity: PRIOR_RECEIPT_SHA256,
      checker_path: PRIOR_CHECKER_PATH,
      checker_sha256: PRIOR_CHECKER_SHA256,
      cycle_id: PRIOR_CYCLE_ID,
    },
    reviewed_cycle: {
      id: cycle.id,
      event_id: event.id,
      prior_cycle_id: PRIOR_CYCLE_ID,
      outcome: cycle.outcome,
      reviewed_at: cycle.reviewed_at,
    },
    next,
    qualification: {
