#!/usr/bin/env node
/**
 * needs.mjs — write data/NEEDED.md, the human photo worklist.
 *
 * For every card still missing a face, it lists the exact name, which kind of
 * photo, roughly what year the portrait should be from, and the exact filename
 * to save it as. Grab the photo, drop it in images/ with that name, run
 * `node scripts/adopt.mjs`, and it appears on the wall.
 *
 *   node scripts/needs.mjs
 */
import { readFile, writeFile } from "node:fs/promises";

const midYear = (years) => {
  const ys = (String(years || "").match(/(?:19|20)\d\d/g) || []).map(Number);
  return ys.length ? Math.round((Math.min(...ys) + Math.max(...ys)) / 2) : 0;
};

const s = JSON.parse(await readFile("data/specimens.json", "utf8"));
const rows = s.filter((c) => !c.still || !c.portrait);
let nStill = 0, nPort = 0;
const body = [];
for (const c of rows) {
  const id = c.id.toLowerCase();
  body.push(`### ${c.id} — ${c.character}`);
  body.push(`*${c.actor} · ${c.production} · ${c.years}*`);
  if (!c.still) { nStill++; body.push(`- [ ] **STILL** — an in-character shot of ${c.character} → save as \`images/${id}-still.jpg\``); }
  if (!c.portrait) {
    nPort++;
    const y = midYear(c.years);
    body.push(`- [ ] **PORTRAIT** — a photo of ${c.actor}${y ? ` (ideally from around ${y}, when they played the role)` : ""} → save as \`images/${id}-portrait.jpg\``);
  }
  if (c.link) body.push(`- reference: ${c.link}`);
  body.push("");
}

const out = [
  "# NEEDED — the photo worklist",
  "",
  `${rows.length} of ${s.length} cards still want a face: **${nStill} stills**, **${nPort} portraits**.`,
  "",
  "**How to fill one by hand:**",
  "1. Find the photo (the card's reference link is a good start).",
  "2. Save it into `images/` with the exact filename shown below.",
  "   - Front of a card = the in-character **still**; back = the actor **portrait**.",
  "3. Run `node scripts/adopt.mjs` — it wires every hand-added file onto the wall",
  "   and logs it in the provenance ledger. Commit, and it's live on the next deploy.",
  "",
  "_(This file is generated by `node scripts/needs.mjs`.)_",
  "",
  "---",
  "",
  ...body,
];
await writeFile("data/NEEDED.md", out.join("\n"));
console.log(`data/NEEDED.md written: ${rows.length} cards need art (${nStill} stills, ${nPort} portraits).`);
